### ISSUE TITLE
Class hierarchy bug in DIDLObject hasProperty, getFirstProperty, etc.

### ISSUE THREAD

**Issue by dkokic** [4thline/cling#107]
The following code 

    java.net.URI albumArtUri = albumContainer.getFirstPropertyValue(DIDLObject.Property.UPNP.ALBUM_ART_URI.class); 

sets `albumArtUri` to `null`, even thought `albumContainer.getProperties()` contains one object with description "albumArtURI". 

After some analysis it came out that there is bug caused by the switch of `propertyClass` and `property`, like for example in the following method:

    public boolean hasProperty(java.lang.Class<? extends Property> propertyClass) {
        for (Property property : getProperties()) {
            if (property.getClass().isAssignableFrom(propertyClass)) return true;
        }
        return false;
    }

Here we want to iterate through the properties and look for an object which is either of the type propertyClass, or a subclass of it. Unfortunately, the code is doing something else: looking for a property object which is either of the type propertyClass, or a superclass of it. That is obviously not 100% correct.

Instead of `property.getClass().isAssignableFrom(propertyClass)` we have to use `propertyClass.isAssignableFrom(property.getClass())`, or even shorter `propertyClass.isInstance(property)`.

Preparing pull request ...

**Comment by ened** [comment]
Let's try to get the second case solved as well, then it can be considered for merge. We should try to cover it well with tests.

**Comment by ened** [comment]
Merged #108, thank you.
Please let me know the conclusion regarding the "open issue" you mentioned above.

**Comment by christianbauer** [comment]
No response, closing.
