### ISSUE TITLE
Play local device media over DLNARendere?

### ISSUE THREAD

**Issue by vikasgoyal88** [4thline/cling#113]
I am trying to play android local media on DLNA renders.

I am currently able to play any global visible media on DLNA renderer which have URI starts with http://172_168.1.1:4566/content_media/file1297834.mp3 this media is also play on any web browser, But when I try to play local media which have file URI like file;//storage/content/media/file.mp3; is not playing on DLNA Renderer. I am aware of that local file need to remotely visible for playing so I have try some options: -

First One I open a android socket and write file into output stream of socket.

But it is not playable on DLNA device. I think it is because android socket write row data into out put stream which DLNA renderer is not able to read.

Second I try with "https://github.com/julesbou/simple-framework" simple framework, It also help to open socket

with it some times media will play on DLNA renderer but it not at every time. and other problem with it is that it is not taking media item METADATA.

Please suggest some solution for the problem

**Comment by vshivam** [comment]
To be able to play media from your phone, you need the file to be hosted via a server on your phone. A simple solution is to embed an http server which serves those files for you. Take a look at NanoHttpd for instance : https://github.com/NanoHttpd/nanohttpd

**Comment by avikasgoyal** [comment]
Thanks for the response!

As I mention you I have already tried the solution by creating my own socket and host the file own server but the socket which I have created is destorying every time after certain period of time.

and the other problem in the hosting is that DLNA renderer is not able to read metadata of media by this it is just playing a file which have no name, duration and other required parameters.

Please suggest some DLNA renderer related server implementation if you have worked on.

Thanks

**Comment by vshivam** [comment]
I have used NanoHttpd to serve files for a Media Renderer. Here's a relevant stackoverflow answer : http://stackoverflow.com/questions/19359304/how-to-serve-a-file-on-sdcard-using-nanohttpd-inside-android

**Comment by kevinshine** [comment]
Hi.
I'm using jetty for the HTTP Server in my application and it used in cling too.
You should subscribe to the AVtransport service of the DMR and parse LastChange  value by DIDLParser. 
If the metadata is not null,you can obtain DIDLContent object and it has all your need.

**Comment by ened** [comment]
Thanks @kevinshine & @vshivam for helping out. I think this issue is closed.
