### ISSUE TITLE
Avtransport Callbacks missing in cling-support-2.0.1.jar

### ISSUE THREAD

**Issue by geroyche** [4thline/cling#117]
I am currently working on a project, and I noticed that 

org.fourthline.cling.support.avtransport.callback.Previous 
org.fourthline.cling.support.avtransport.callback.Next 

exist in the source on github, and in the documentations, but they are not part of the latest downloadable release. I cannot say whether more classes are missing or not.

Could you update the jar files please?

**Comment by ened** [comment]
True, those classes have been added after the 2.0.1 release.

Once @christianbauer is back, he'll surely release 2.0.2 and include them. Meanwhile, please build the project on your machine and install it using "mvn clean install".

**Comment by ened** [comment]
@geroyche see https://github.com/ened/cling/tree/develop for a temporary maven repo with a few merged PRs.

**Comment by geroyche** [comment]
@ened thanks.
pardon my ignorance, but i am completly new to maven (and gradle).
trying to build your fork but i am hitting a brick wall.
i downloaded cling, installed gradle, created this build.gradle:

apply plugin:'java'
repositories {
    mavenCentral()
    maven {
        url 'https://raw.github.com/ened/cling/mvn-repo'
    }
    maven {
 	url 'http://4thline.org/m2'
    }
}
dependencies {
    compile('org.fourthline.cling:cling-core:2.0.1-SR-SNAPSHOT')
    compile('org.fourthline.cling:cling-support:2.0.1-SR-SNAPSHOT')
}

all i get is an empty jar that is named after project folder.
what am i missing?
mind to share a complete build.gradle that will output the desired cling jars?

thank you in advance :)

**Comment by ened** [comment]
The cling-jars are there (in Snapshot versions) already, you don't need to compile them again. If you include them manually, simply open the raw.github.com link in a browser to download.
If you don't use maven or gradle, that would be how you get them.

**Comment by geroyche** [comment]
finally figured it out. added a task to gradle that downloads all dependencies. that did the trick for me (manually browsing that raw github link returns error code 400).

thanks for your help!

**Comment by ened** [comment]
Close the issue please.
