### ISSUE TITLE
500 internal server sometimes coming?

### ISSUE THREAD

**Issue by aravindasthme** [4thline/cling#124]
i checked in bubble upnp ,it works fine,when i try to play it is failing..it always shows 500 internal server error

		  Play play= new Play(m_avtransportService) {
             @Override
			public void success(ActionInvocation invocation) {
				super.success(invocation);
				fireOnPlayingEvent();              
                Log.d(TAG,"Play is sucess");
			}

            
             @Override
			public void failure(ActionInvocation invocation, UpnpResponse response, String defaultMsg) {

                 fireOnFailEvent(invocation.getAction(), response,
						Play.class.getSimpleName() + ":" + defaultMsg);

                }

		};

        m_controlPoint.execute(play);

i was using cling 1 ,recently i migrated to cling 2.00

i am trying to play when the setUri is sucess,

this is my meta data
<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="audio-item-293" parentID="2" restricted="0"><dc:title>Deeyaalo Deeyaalo - TamilTunes.com</dc:title><dc:creator>Oranthanadu Gopu</dc:creator><upnp:class>object.item.audioItem.musicTrack</upnp:class><upnp:album>Kayal (2014)</upnp:album><upnp:artist role="Performer">Oranthanadu Gopu</upnp:artist><res protocolInfo="http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01500000000000000000000000000000" size="8680661" duration="0:03:32">http://192.168.43.121:57645/external/audio/media/230.mp3</res></item></DIDL-Lite>

**Comment by ened** [comment]
@aravindasthme Thank you for your report. However, it is missing a LOT of information plus we also do not have the resources to support 3rd party app integrations. This project can only support you if you have found a issue directly in Cling.

In order to help you, please copy the `adb logcat` stack traces of the server / renderer side as well.
Also, you should try the method using the cling workbench.

**Comment by aravindasthme** [comment]
@ened Thank for your reply,I was using httpServer for media sever in cling 1.0.0,after migrating cling 2.0.0 still i am using the httpServer.

logs for skipping..

04-08 15:39:57.048  21714-21798/com.libre.client.activity D/com.app.dlna.dmc.processor.impl.DMRProcessorImpl﹕ Fireonplayingevent
04-08 15:39:57.070  21714-21782/com.libre.client.activity V/com.app.dlna.dmc.processor.impl.DMRProcessorImpl﹕ Success setting URI to DMR
04-08 15:39:57.070  21714-21782/com.libre.client.activity E/com.app.dlna.dmc.processor.impl.DMRProcessorImpl﹕ Sucessfully setting setTransport
04-08 15:39:57.070  21714-21782/com.libre.client.activity E/com.app.dlna.dmc.processor.impl.DMRProcessorImpl﹕ Trying to play
04-08 15:39:57.093  21714-22289/com.libre.client.activity I/System.out﹕ GET '/audio-item-78'
04-08 15:39:57.094  21714-22289/com.libre.client.activity I/System.out﹕ HDR: 'istimeseek' = '0'
04-08 15:39:57.094  21714-22289/com.libre.client.activity I/System.out﹕ HDR: 'host' = '192.168.1.139:11891'
04-08 15:39:57.094  21714-22289/com.libre.client.activity I/System.out﹕ HDR: 'accept-encoding' = 'gzip,deflate'
04-08 15:39:57.094  21714-22289/com.libre.client.activity I/System.out﹕ HDR: 'user-agent' = 'stagefright/1.2 (Linux;Android'
04-08 15:39:57.094  21714-22289/com.libre.client.activity I/System.out﹕ HDR: 'connection' = 'keep-alive'
04-08 15:39:57.156  21714-21819/com.libre.client.activity W/PLAY VIEW﹕ onActionFail:Play:Error: Action Failed (HTTP response was: 500 Internal Server Error)
04-08 15:39:57.157  21714-21819/com.libre.client.activity E/com.app.dlna.dmc.processor.impl.DMRProcessorImpl﹕ Trying once again
04-08 15:39:57.194  21714-22290/com.libre.client.activity I/System.out﹕ GET '/audio-item-78'
04-08 15:39:57.195  21714-22290/com.libre.client.activity I/System.out﹕ HDR: 'istimeseek' = '0'
04-08 15:39:57.195  21714-22290/com.libre.client.activity I/System.out﹕ HDR: 'host' = '192.168.1.139:11891'
04-08 15:39:57.195  21714-22290/com.libre.client.activity I/System.out﹕ HDR: 'accept-encoding' = 'gzip,deflate'
04-08 15:39:57.195  21714-22290/com.libre.client.activity I/System.out﹕ HDR: 'user-agent' = 'stagefright/1.2 (Linux;Android'
04-08 15:39:57.195  21714-22290/com.libre.client.activity I/System.out﹕ HDR: 'connection' = 'keep-alive'
04-08 15:39:57.844  21714-21802/com.libre.client.activity D/com.app.dlna.dmc.processor.impl.DMRProcessorImpl﹕ postion info249
04-08 15:39:57.847  21714-21802/com.libre.client.activity D/com.app.dlna.dmc.processor.impl.DMRProcessorImpl﹕ postion info249
04-08 15:39:57.847  21714-21802/com.libre.client.activity D/com.app.dlna.dmc.processor.impl.DMRProcessorImpl﹕ Total track duration00:04:09
04-08 15:39:57.848  21714-21714/com.libre.client.activity I/PLAY VIEW﹕ progress:0 duration:322

**Comment by ened** [comment]
Again, you should check the server side more - and if possible, catch the "Internal Server Error" using a breakpoint or detail stack trace.

The details you wrote above don't help.

**Comment by aravindasthme** [comment]
@ened  hey do you know what are the audio formats will be supported by cling ?

**Comment by ened** [comment]
You should refer to the dlna spec on supported formats and your hardware. It got nothing to do with cling.

**Comment by aravindasthme** [comment]
@ened Thank u so much
