### ISSUE TITLE
Question : Is there an easy way to limit discovery to RootDevices?

### ISSUE THREAD

**Issue by hmerk** [4thline/cling#129]
UPnP Device Architecture allows different search targets for the ST header, but I can not find an option to specify a discovery using "ST:upnp:rootdevice". It seems, that only "ST:ssdp:all" is alowed.

Can anybody give me a hint ?

Best
Hans-Jörg

**Comment by ened** [comment]
@hmerk Found a solution already?

**Comment by hmerk** [comment]
@ened
Yes and no.
I found a way to patch JUPnP / CLING to send discovery as needed, but I guess this was not a solution to comit to the public.
Now I changed my openHAB2 WeMo binding to not rely on UPNP.
Who knows, what else Belkin might change with future firmware versions, causing problems again.

**Comment by christianbauer** [comment]
No need to patch anything, there is a perfectly good and documented ControlPoint#search(STHeader) method in Cling. Don't know of the bastard JUPnP fork removed it.

**Comment by hmerk** [comment]
@christianbauer 
Perhaps I am missing something, but all I can find is search(STALLHeader), which seems to be the default search and is limited to ST:ssdp:all.
Can you give me an example, how to to a search with
ST:upnp:rootdevice ?

**Comment by christianbauer** [comment]
https://github.com/4thline/cling/blob/206fd06b551c60151e2c785cd8b2aa45a9a0a54b/core/src/test/java/example/controlpoint/SearchExecuteTest.java

**Comment by christianbauer** [comment]
http://4thline.org/projects/cling/core/manual/cling-core-manual.html#javadoc.example.controlpoint.SearchExecuteTest

**Comment by christianbauer** [comment]
And if you are using the JUPnP fork of Cling, you can please go ahead and ask the openhab/Telekom guys for help.
