### ISSUE TITLE
Switch to another wifi home network, media render device cannot be found again

### ISSUE THREAD

**Issue by SylvanHuang** [4thline/cling#134]
Hi, everyone. I'm doing some jobs with cling libs. But when I use cling 2.0.1, I found that when I switch my TV set box from one to another wifi home network, it can't work normally. Originally, I used the cling 1.0.5 and it worked well. But I want to change the nofity period, so I change to use 2.0.1.  But now I'm confused but I didn't change too much codes. If somebody knows how to solve it, give me a help. Thanks.

**Comment by SylvanHuang** [comment]
If I restart the TV set box, however, it can work again.

**Comment by praveensleeps** [comment]
I am also noticing this problem, As my App starts failing to send M search request if I change the Connection to the other wifi/P2P nework AP.

**Comment by vikasgoyal88** [comment]
Hi All,

Cling library is only useful for sharing media in same network.
In DLNA  it will not reachable outside the network.

Thanks

On 20 June 2015 at 00:55, Praveena <notifications@github.com> wrote:

> I am also noticing this problem, As my App starts failing to send M search
> request if I change the Connection to the other wifi/P2P nework AP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/4thline/cling/issues/134#issuecomment-113613685>.
>



-- 
*Best Regards,*

*Vikas Goyal | Associate - IT **Daffodil Software Ltd.*

*15th Floor, Building A3DLF Silokhera SEZ, Sec-30*
*Gurgaon - 122001, Haryana*

**Comment by SylvanHuang** [comment]
I know what vikasgoyal88 means. But what I means is that, I just close the wifi router and then open it again. The wifi connection will be built again and I have done something to restart the media render service. I'm sure the media render and control point is in the same network. But the media render can't work. Thanks.

**Comment by SylvanHuang** [comment]
we solve this problem with the changes below. 
Modify the stop method in AsyncServletStreamServerImpl.java, like this:
    synchronized public void stop() {
         //getConfiguration().getServletContainerAdapter().removeConnector(hostAddress, localPort);
 	 getConfiguration().getServletContainerAdapter().removeConnector(hostAddress, getConfiguration().getListenPort());
    }
then it can work better.

**Comment by SylvanHuang** [comment]
we do some modification to the stop method of AsyncServletStreamServerImpl.java, then it works better. Codes are below.
synchronized public void stop() {
        //getConfiguration().getServletContainerAdapter().removeConnector(hostAddress, localPort);
       getConfiguration().getServletContainerAdapter().removeConnector(hostAddress,                 getConfiguration().getListenPort());
    }
Wait for better solutions. Thanks.

**Comment by christianbauer** [comment]
Incomplete problem description, the "solution" is certainly wrong. Closing.
