### ISSUE TITLE
Compilation Error while building Cling Core: FixedSunURLStreamHandler

### ISSUE THREAD

**Issue by praveensleeps** [4thline/cling#136]
I am trying to build the cling library with the source code from github and I am getting compilation error 1. cannot resolve symbol method 
2.sun.net.www.protocol.http.Handler() cannot resolve the symbol  Handler

**Comment by christianbauer** [comment]
What JDK is this?

**Comment by Aguaimama** [comment]
I just removed the FixedSunURLStreamHandler.java from the project seems it also can work well.I used in Android  Application.

**Comment by christianbauer** [comment]
No response, closing.
