### ISSUE TITLE
Adapter not found

### ISSUE THREAD

**Issue by thingshares** [4thline/cling#138]
Hi,
I've got a problem while diagnosing available adapters on an XP machine - the Ethernet adapter had a valid network address (192.168.0.7) but iface.isLoopback() reported true.
My patch on 2.0.1 release (in cling-core, NetworkAddressFactoryImpl.java)  
protected boolean isUsableNetworkInterface(NetworkInterface iface) throws Exception {
....
        if (iface.isLoopback()) {
// Change from here
        	List<InterfaceAddress> addrs = iface.getInterfaceAddresses();
        	for (InterfaceAddress ia : addrs)
        	{
                if (ia.getAddress().toString().indexOf("127.0.0.1") >= 0)
                {
               		log.finer("Skipping network interface (ignoring loopback): " + iface.getDisplayName());
            		return false;
                }
        	}
// to here
        }
...
Thank you, bye !

**Comment by ened** [comment]
If this is a patch, we welcome it, but require it as Github pull request so others can comment it directly. Thanks for your understanding.
