### ISSUE TITLE
It crashed and report the action can not be null

### ISSUE THREAD

**Issue by Chronoer** [4thline/cling#139]
Hi all,

I got a crash problem sometimes, I checked the log and code and I can't figure out the problem, please help me!

crash log:

        java.lang.IllegalArgumentException: Action can not be null
                org.fourthline.cling.model.action.ActionInvocation.<init>(ActionInvocation.java:76)
                org.fourthline.cling.model.action.ActionInvocation.<init>(ActionInvocation.java:46)
                org.fourthline.cling.support.contentdirectory.callback.Browse.<init>(Browse.java:72)
                org.fourthline.cling.support.contentdirectory.callback.Browse.<init>(Browse.java:63)
                com.mightyrc.app.services.BrowseUpnpServerFile.<init>(BrowseUpnpServerFile.java:21)
                com.mightyrc.app.activity.cast.CastBroweFileActivity$1.onServiceConnected(CastBroweFileActivity.java:306)

my code:

        private ServiceConnection mServiceConnection = new ServiceConnection() {
                public void onServiceConnected(ComponentName className, IBinder service) {
        	        mUpnpService = (AndroidUpnpService) service;
        	
                	if(mCastDevice != null && mCastDevice.getDevice() != null){
	                	Service containerService = mCastDevice.getDevice().findService(new UDAServiceType("ContentDirectory"));
	                	if(containerService == null || mUpnpService == null || mUpnpService.getControlPoint() == null){
	        	        	return;
        	        	}
	        
	                	mUpnpService.getControlPoint().execute(new BrowseUpnpServerFile(containerService, mContainerId, BrowseFlag.DIRECT_CHILDREN, mOnBrowseFileListener));
                                //^^^^^^^crash on this line^^^^^^^^^^^
                	}
                }

        
                public void onServiceDisconnected(ComponentName className) {
        	        mUpnpService = null;
                }
            };

Thank you.

**Comment by ened** [comment]
Contents of `BrowseUpnpServerFile.java`?

**Comment by christianbauer** [comment]
This is not stackoverflow.
