### ISSUE TITLE
JCenter/MavenCentral

### ISSUE THREAD

**Issue by chrisjenx** [4thline/cling#141]
I think it would be prudent to deploy to jCenter or MavenCentral.
As much as you hope to be around if a few years, I don't want my dependencies relying on a single point of failure.

**Comment by jitpack-io** [comment]
Hi all
In the meantime cling is available as a dependency from: https://jitpack.io/#4thline/cling/2.0.1

**Comment by christianbauer** [comment]
I've been running webservers since 1995, I think I'll manage a few more years.

**Comment by mateusgrb** [comment]
Deploying to jCenter/Maven Central would be nice. Thanks @jitpack-io for the alternative.

**Comment by mateusgrb** [comment]
@jitpack-io trying to compile from jitpack I get this error: Failed to resolve org.seamless:seamless-http:1.1.1

I tried to import that dependency but couldn't find it. Any suggestions on what I'm missing?
