### ISSUE TITLE
Jetty Dependency

### ISSUE THREAD

**Issue by chrisjenx** [4thline/cling#142]
What specifically is required from Jetty for Cling? 
Cling is great but when it takes up 17% of the Android method dex limit, it makes a bit heavy weight.

```bash
3367     org.fourthline.cling
6886     org.eclipse
893      org.seamless
= 11,146 - 65,536 (dex limit)
=~ 17%
```

Are there possibilities to modulise the code? Or use a lighter weight network client?

**Comment by bubbleguuum** [comment]
If that's a problem  you can easily dex jetty jars,  put it in a APK that you dynamically load when starting your app. Giving the benefit 7K methods that will not count against the dex limit (which is quiclky reached anyway these days) and will not impact build times.
Jetty is used as an http client and server (to handle incoming requests). Cling is modular and anything can be replaced. Prior to Cling v2, Apache HttpComponents was used instead, as both a client and server. Jetty is really useful if you also need it to implement an UPnP AV media server.

**Comment by chrisjenx** [comment]
I see, are you taking about multi dex or proguard an Android version and
include that?

**Comment by bubbleguuum** [comment]
Yes, I'm talking about multi-dexing but in a manual way (you have to only do it once or whenever you update jetty) with manual loading at runtime. This has the advantage of not impacting build time at all (vs automatic multi-dex support in Android Support). I'm using this trick in BubbleUPnP, a large app way over the 64K limit, as well as a myriad of Libraries, including Calligraphy :) :

1.  use  'dx --dex' on all jetty jars to generate an APK. zipalign it
2.  put the generated APK in the assets folder of your Android project
3.  load the APK dynamically on app startup with these helper funcs

```
@SuppressLint({ "NewApi", "SdCardPath" })
	static public void dexTool(Context context, String assetApkFilename) throws IOException, NoSuchFieldException, IllegalAccessException, IllegalArgumentException{
		
		File dexDir = new File(context.getFilesDir(), "dlibs");
		dexDir.mkdir();
		File dexFile = new File(dexDir, assetApkFilename);

		InputStream ins = context.getAssets().open(assetApkFilename); // throws IOException
		if (dexFile.length() != ins.available()) {
			FileOutputStream fos = new FileOutputStream(dexFile);
			byte[] buf = new byte[4096];
			int l;
			while ((l = ins.read(buf)) != -1) {
				fos.write(buf, 0, l);
			}
			IOUtils.closeQuietly(fos);
		}
		IOUtils.closeQuietly(ins);
		
		dexTool(context, dexFile);

	}
	
	static public void dexTool(Context context, File apkFile) throws NoSuchFieldException, IllegalAccessException, IllegalArgumentException  {

		ClassLoader cl = context.getClassLoader();
		ApplicationInfo ai = context.getApplicationInfo();
		String nativeLibraryDir = null;
		nativeLibraryDir = ai.nativeLibraryDir;

		File dexOpt = new File(apkFile.getParent(), "opt");
		dexOpt.mkdir();

		DexClassLoader dcl = new DexClassLoader(apkFile.getAbsolutePath(), dexOpt.getAbsolutePath(), nativeLibraryDir, cl.getParent());

		Field f = ClassLoader.class.getDeclaredField("parent");
		f.setAccessible(true);
		f.set(cl, dcl);	
	
	}
```

**Comment by chenzj-king** [comment]
Use the Android Studio & Gradle is so easy to deal with the 65K problem.
first you shoule dependencies the multidex.
compile 'com.android.support:multidex:1.0.0'
![qq 20150828191624](https://cloud.githubusercontent.com/assets/11900696/9545212/ef3b23b4-4db9-11e5-98cb-1fc46e66db66.jpg)

and then you setting the deafultConfig
multiDexEnabled = true
![qq 20150828191700](https://cloud.githubusercontent.com/assets/11900696/9545248/2d1d045e-4dba-11e5-933b-7c23ff5a0f03.jpg)
in the end.you should use the MultiDexApplication or change you customApplication like this
 @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
![qq 20150828192013](https://cloud.githubusercontent.com/assets/11900696/9545266/6ada5698-4dba-11e5-80d0-72611b546ea1.jpg)

that's all.i know about that in https://developer.android.com/tools/building/multidex.html
you can try to read this article.

**Comment by chrisjenx** [comment]
I know all that was just trying to avoid multi dex as it significantly
slows downs builds.

**Comment by chenzj-king** [comment]
you right.we should avoid multi dex.our team project 100K method now.It was the reson for I used the Android Studio.Of course the Android Studio it's great.

**Comment by ened** [comment]
@chrisjenx let's go with @bubbleguuum answer and close this issue. We are happy about contributions for newer or "slimmer" HTTP components.
