### ISSUE TITLE
SetAVTransportURI send Upnp Response = 500 Internal server error on xbox one

### ISSUE THREAD

**Issue by smardine** [4thline/cling#143]
Hi, i've just test your cling package to send video from my android phone to my xbox one.
The xbox one is well detected as MediaRenderer as you can see in the xml bellow

![xbox one description](https://cloud.githubusercontent.com/assets/13467840/9064053/0344d528-3acb-11e5-828f-57509d355a27.png)

I try to send an url to my xbox one with the code bellow:
 public String play(String uriToPlay)
    {
	//uriToPlay = "http://www.duorimes.siquiere.fr/wa_files/Il_20camino.flv", i've also tried other url of video file, same result

		ServiceType serviceType =  ServiceType.valueOf(DLNAConst.AVTransport1);
        if (getDevice().isFullyHydrated()) {

            Service s = getDevice().findService(serviceType);           
       
			Action setAVTransportURIAction = s.getAction("SetAVTransportURI");

            ActionInvocation setAVTransportURIInvocation=null;
            try {
             
                setAVTransportURIInvocation = new ActionInvocation(setAVTransportURIAction);
                setAVTransportURIInvocation.setInput("InstanceID",new UnsignedIntegerFourBytes(0)); // Can throw InvalidValueException
                setAVTransportURIInvocation.setInput("CurrentURI", uriToPlay);
                setAVTransportURIInvocation.setInput("CurrentURIMetaData", "");

            }catch (final Exception ex)
            {
                _context.runOnUiThread(new Runnable() {
                    public void run() {
                        Toast.makeText(
                                _context,
                                "Discovery failed of '" + device.getDisplayString() + "': "
                                        + (ex != null ? ex.toString() : "impossible de lancer l'invocation setAVTransportURIInvocation"),
                                Toast.LENGTH_LONG
                        ).show();
                    }
                });
            }
         
           _upnpService.getControlPoint().execute(setAVTransportURICallBack);
		   
           
        }

        return retour;
}

It's always the overrided method failure wich is fired  with error code 500: Internal server error

Do you ever experience it?
Thanks for help and congrats for your job

**Comment by christianbauer** [comment]
Got to stackoverflow, this is not a user help forum.
