### ISSUE TITLE
Actions not found on android

### ISSUE THREAD

**Issue by deblockt** [4thline/cling#144]
Hello,

I try to read a video on a remote device. 
I have done a java/PC app who work perfectly.

I use the same code, on android app, but this doesn't work.
When i find services, they have no actions. So when I do 
```
new Play(service)
```
It failed, because service have not actions.

Have you an idea, why my devices has no actions only on android?

Thanks.

**Comment by deblockt** [comment]
I have found the glitch.

Each device is added two time : 
   - first time, without actions
   - second time with actions

The method BrowseRegistryListener.deviceAdded is called two time for each remote device. I don't understand why. 
My listener extends DefaultRegistryListener, and my AndroidUpnpService is the AndroidUpnpServiceImpl.

Thanks

**Comment by ened** [comment]
The device is not fully hydrated - this is by design. See
https://github.com/4thline/cling/blob/6d582af927d504e669d140ad96bb2e5b47efe0ea/core/src/main/java/org/fourthline/cling/registry/Registry.java for some details.

Please re-open if I misunderstood.
