### ISSUE TITLE
Can't load the jetty.server.Server

### ISSUE THREAD

**Issue by chenzj-king** [4thline/cling#146]
I ues the Android Studio 1.4.3 SDK 22 and Gradle android plugin 1.3.0.
when i run in my phone.it put some error message like this
![jetty server not find](https://cloud.githubusercontent.com/assets/11900696/9546831/8bba9306-4dc8-11e5-9b36-a38b4aa8ab93.jpg)

the cling-lib and the jetty-lib i use the local dependencies.
![cling-lib](https://cloud.githubusercontent.com/assets/11900696/9546858/ac0b6da6-4dc8-11e5-9aed-7d977a2bd7e2.jpg)

Android studio show me should setting the packagingOptions when i build the project.so i has change the app module build.gradle
![packaginoption](https://cloud.githubusercontent.com/assets/11900696/9546875/e12da35a-4dc8-11e5-80de-61c09d2c4256.jpg)

also it build success.but will crach by NoClassFoundDefError.and then i decompile the dex like this
![dextojar](https://cloud.githubusercontent.com/assets/11900696/9546924/2c1c53a2-4dc9-11e5-89ae-db4b94b8e982.jpg)

the class is in the dex.but It can't load the jetty.server.Server.I think is maybe i setting the packagingOptions bring about this problem.can you guide me to deal with this problem.thanks.

**Comment by chenzj-king** [comment]
After read you blog.I know that use the jetty8 libraries.i instead the jetty libraries will work.but i find i can't find the dms in other phone in the same Lan.I use you brower and light demo apk can't discovery the light too.can you give me some direction?Thanks

**Comment by christianbauer** [comment]
Go to stackoverflow.
