### ISSUE TITLE
Error browsing folders on Seagate GoFlex Home NAS

### ISSUE THREAD

**Issue by mntgoat** [4thline/cling#150]
I have a user with a Seagate GoFlex Home NAS and he gets an error when browsing folders. He can see the initial list of folders but going into any of them gives an error. He has no way to capture logs since it is on Android. Do you maybe have a sample app he can try? 

I'm attaching a screenshot of the error my app gives which is really just the error it gets from cling. Not sure how helpful that will be. 

Thanks. 
![screenshot from 2015-11-17 11-16-51](https://cloud.githubusercontent.com/assets/1638377/11218878/1862263c-8d1d-11e5-8f65-cca8d611fbd3.png)

**Comment by ened** [comment]
Without logs this will be difficult to research. I'm closing this issue until you can help to provide detailed logs and XML fragments from that NAS box.

The error message talks about undefined `sec` namespace, which is probably vendor-specific behavior.
