### ISSUE TITLE
META-INF/beans.xml in cling-support should be removed

### ISSUE THREAD

**Issue by tao1** [4thline/cling#162]
Hello,

_META-INF/beans.xml_ in cling-support collides with _META-INF/beans.xml_ in cling-core when embedding both libraries in an android project.
Sorry I have no more the gradle error message caused by that collision because I solved it on my side by removing the empty _META-INF/beans.xml_ of cling-support.
But I report this bug for the community.
Notice I got this error with release 2.1.0.

Kind regards,

Laurent.

**Comment by ened** [comment]
Try adding:

```
android {
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/beans.xml'
        exclude 'about.html'
    }
}
```

**Comment by tao1** [comment]
Thanks for the tip ! and response time ;)
But notice META-INF/beans.xml of cling-support is empty.
