### ISSUE TITLE
Uncaught exception 'org.fourthline.cling.transport.RouterException'

### ISSUE THREAD

**Issue by PpradeepkumarR1993** [4thline/cling#222]
Getting crash on 
`java.lang.RuntimeException: Fatal error while executing protocol 'SendingSearch': org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: ReadLock
--
1 | at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:61)
2 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
3 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
4 | at java.lang.Thread.run(Thread.java:762)
5 | Caused by: org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: ReadLock
6 | at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:499)
7 | at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:510)
8 | at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:305)
9 | at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
10 | at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
11 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
13 | at java.lang.Thread.run(Thread.java:762)

0 | at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
1 | at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)

0 | at android.os.MessageQueue.nativePollOnce(Native Method)
1 | at android.os.MessageQueue.next(MessageQueue.java:323)
2 | at android.os.Looper.loop(Looper.java:136)
3 | at android.app.ActivityThread.main(ActivityThread.java:6688)
4 | at java.lang.reflect.Method.invoke(Native Method)
5 | at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
6 | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
`

**Please help us out, how we can get rid of this crash from "cling-core-2.1.2-SNAPSHOT.jar" library.**

**Comment by PpradeepkumarR1993** [comment]
Guys, Please help me out, this is causing crash with many users.

**Comment by swy0710** [comment]
I am facing the same issue.
Please help.

**Comment by mehao** [comment]
why closed this issue?

**Comment by KumariAnjuThakur** [comment]
I am still facing this Exception, Why closed this issue?

**Comment by renkuo** [comment]
> I am still facing this Exception, Why closed this issue?

Have you solved the problem yet?

**Comment by renkuo** [comment]
> why closed this issue?

Have you solved the problem yet?

**Comment by davidkocnar** [comment]
Still problem. I assume they abandoned it ...

**Comment by qq3429** [comment]
这个bug 我尝试解决了,  等我消息

**Comment by 1programmer2dfg3** [comment]
> 这个错误我正在尝试解决，等我消息

怎么样，解决了吗，可以的话帮忙发下解决方案和代码，谢谢
