### ISSUE TITLE
Exception sending datagram to: /239.255.255.250

### ISSUE THREAD

**Issue by ingsaurabh** [4thline/cling#224]
I am seeing following exception Android 8.0.0, and not on other android versions, and no device is detected after that, one solution is to restart the DLNA device then the device is detected.

> DatagramIO: Exception sending datagram to: /239.255.255.250: java.io.IOException: sendto failed: EPERM (Operation not permitted)
>                                                                    java.io.IOException: sendto failed: EPERM (Operation not permitted)
>                                                                        at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:603)
>                                                                        at libcore.io.IoBridge.sendto(IoBridge.java:571)
>                                                                        at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:124)
>                                                                        at java.net.DatagramSocket.send(DatagramSocket.java:721)
>                                                                        at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
>                                                                        at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
>                                                                        at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
>                                                                        at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
>                                                                        at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
>                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>                                                                        at java.lang.Thread.run(Thread.java:764)
>                                                                     Caused by: android.system.ErrnoException: sendto failed: EPERM (Operation not permitted)
>                                                                        at libcore.io.Linux.sendtoBytes(Native Method)
>                                                                        at libcore.io.Linux.sendto(Linux.java:225)
>                                                                        at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:304)
>                                                                        at libcore.io.IoBridge.sendto(IoBridge.java:569)
>                                                                        at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:124) 
>                                                                        at java.net.DatagramSocket.send(DatagramSocket.java:721) 
>                                                                        at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159) 
>                                                                        at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150) 
>                                                                        at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309) 
>                                                                        at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91) 
>                                                                        at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54) 
>                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
>                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
>                                                                        at java.lang.Thread.run(Thread.java:764)

**Comment by pcrepieux** [comment]
I started playing with cling a few day ago and I also noticed such a log on a recent device that I don't see on older Android version. This is likely due to the library attempting to multicast a packet when attached to the mobile network. As this is anyway not allowed, it seems the network driver now reports EPERM which the framework forwards by throwing an IOException. 

I may be wrong or miss something but I guess getBindAddresses in NetworkAddressFactory (whose result is used by startAddressBasedTransport in RouterImpl to initialize DatagramIO) should not contains the mobile network interface and mostly if the interface doesn't have the IFF_MULTICAST flag. I have seen a check on this flag somewhere else in the code, but I believe some additional ones could be added.
 
Anyway, I think you should be able to get it right by carefully managing the network type within your application and enforce you are on Wifi. 

NB: there might be some others approaches. I don't know cling enough to tell which one is the best suited.
