### ISSUE TITLE
how to do discovery every N second?

### ISSUE THREAD

**Issue by BigGitWorld** [4thline/cling#225]
I'm going to do upnp discovery of some devices (over my router) by android every 30 seconds.
I saw the AndroidUpnpServiceImpl class has createConfiguration() method that return an object from AndroidUpnpServiceConfiguration class.
So I changed return value in getRegistryMaintenanceIntervalMillis method but .
is it true?
please clarify me...
thanks.

**Comment by christianbauer** [comment]
Not a help forum.

**Comment by BigGitWorld** [comment]
at least give me a reference to handle this. I needed it...
