### ISSUE TITLE
upnp does not work in Huawei NXT-L29 (Android 7-API 24)

### ISSUE THREAD

**Issue by BigGitWorld** [4thline/cling#226]
I have a huawei phone with andorid 7 and I used demo application of cling.
My code works perfectly in LG G2 API 19 but does not work in the huawei.
details:
When connect phone's wifi directly to my device (that supports upnp), SSDP Notify message will work (my phone receives notify messages of upnp device).
but when both my phone and device are in a local network (tp-link modem) my phone cannot receive SSDP notify messages. 
why?

**Comment by auxor** [comment]
Some router may block multicast.
