### ISSUE TITLE
pain in the ass to install and compile errors everywhere

### ISSUE THREAD

**Issue by jredfox** [4thline/cling#234]
pain in the ass to install and compile errors everywhere. there is no simple drag and drop the source then start editing there is go into 400 folders determine with your brain is this an insturction folder or is this the actual source where does the actual source begin.

Then when I finally installed all the packages manually it has compile errors everywhere fix your dam project.

Also there is no clear instructions on how to port forward the main point! I just see controlling things not actually creating maintaining and opening ports. 

I see it says java yet there are compile errors everywhere You claimed this also worked in java liar. This is android only

**Comment by spikehip** [comment]
Ok, so I updated my [fork](https://github.com/spikehip/cling) by pulling the master branch from [here](https://github.com/4thline/cling). 

```Andrass-MacBook-Pro:cling andrasbekesi$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
´´´

it is important that you set the location of your android sdk:
```Andrass-MacBook-Pro:cling andrasbekesi$ echo $ANDROID_HOME
/Users/andrasbekesi/Library/Android/sdk
´´´

Also important that you have the Android SDK 15 and tools downloaded and installed. At best you get the Android Studio and let it install everything for you.

then 
```
mvn clean package
[INFO] Reactor Summary:                                                                                                                          
[INFO]                                                                                                                                               
[INFO] Cling .............................................. SUCCESS [  0.089 s]             
[INFO] Cling Core ......................................... SUCCESS [01:11 min]                                                          
[INFO] Cling Demo ......................................... SUCCESS [  0.001 s]                                                
[INFO] Cling Demo Android ................................. SUCCESS [  0.002 s]                                                           
[INFO] Cling Demo Android Browser ......................... SUCCESS [  8.318 s]     
[INFO] Cling Demo Android Light ........................... SUCCESS [  7.167 s]                 
[INFO] Cling Support ...................................... SUCCESS [ 10.383 s]
[INFO] Cling Workbench .................................... SUCCESS [ 10.048 s]                       
[INFO] Cling MediaRenderer ................................ SUCCESS [  1.585 s]             
[INFO] Cling Website ...................................... SUCCESS [  0.001 s]                                      
[INFO] Cling Distribution ................................. SUCCESS [  5.608 s]                                                                    
[INFO] ------------------------------------------------------------------------                                                             
[INFO] BUILD SUCCESS                                                                     
[INFO] ------------------------------------------------------------------------                
[INFO] Total time: 01:55 min                                                             
[INFO] Finished at: 2018-06-25T10:31:46+02:00                                           
[INFO] Final Memory: 81M/1512M                                                                        
[INFO] ------------------------------------------------------------------------
´´´

Oh, and the cling-core lib is meant for use with J2SE.
Hope this helped.

**Comment by spikehip** [comment]
However, an automated build on travis-ci and a badge in the readme would be nice ;)

**Comment by jredfox** [comment]
No f***** android this is a java library let android be optional

**Comment by spikehip** [comment]
get yourself together, man
