### ISSUE TITLE
Unable to initiate network router

### ISSUE THREAD

**Issue by vastheaven** [4thline/cling#55]
Hi Chris,

I am using Samsung Galaxy S3 to run a Cling app. Somehow I met a problem:

02-26 15:48:38.800: I/UpnpServiceImpl(32374): <<< UPnP service started successfully
02-26 15:48:38.960: I/Router(32374): WiFi state changed, trying to enable router
02-26 15:48:38.960: I/Router(32374): Creating Router: org.teleal.cling.transport.RouterImpl
02-26 15:48:38.970: I/NetworkAddressFactory(32374): No network interfaces available
02-26 15:48:38.970: E/Router(32374): Unable to initialize network router: org.teleal.cling.transport.spi.InitializationException: Could not discover WiFi network interface
02-26 15:48:38.970: E/Router(32374): Cause: org.teleal.cling.transport.spi.InitializationException: Could not discover WiFi network interface

I restarted wlan on the phone but the problem remained. After I restarted my phone the problem solved.
This problem does not always occur, but do you know what cause it?

THANKS!

Hao

**Comment by stefano055415** [comment]
I have the same error, can you help me?
